-- ============================================================================
-- DEPRECATED: This file is deprecated
-- ============================================================================
-- 
-- The initialization logic has been consolidated into 01-init-permissions.sql
-- This file is kept for reference but is no longer executed during database setup.
--
-- Please refer to 01-init-permissions.sql for the current database initialization.
-- ============================================================================
