'use client'
import { useState, useContext, useEffect } from 'react'
import { useRouter } from 'next/navigation'
import { useForm } from 'react-hook-form'
import { zodResolver } from '@hookform/resolvers/zod'
import * as z from 'zod'
import { BookingContext } from '../context/BookingContext'
import { useAuthContext } from '../context/AuthContext'
import LocationSearch from './booking/LocationSearch'
import DateRangePicker from './DateRangePicker'
import VehicleTypeSelector from './VehicleTypeSelector'
import { calculateFare } from '../../lib/pricing'
import { createBooking } from '../../services/booking/api'
import PaymentStep from './PaymentStep.new'

[Rest of original component code]